# Generated by Django 3.0.5 on 2020-06-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookimage',
            options={'verbose_name': 'Book Image', 'verbose_name_plural': 'Book Images'},
        ),
    ]
